In [1]:
import numpy as np
import pandas as pd

In [2]:
movie=pd.read_csv(r"C:\Date Science\Mechine Learning\movie_recommandation_dataset\tmdb_5000_movies.csv")
movie.sample(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3202,5000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 35, ""...",NaN,9671,"[{""id"": 242, ""name"": ""new york""}, {""id"": 549, ...",en,Crocodile Dundee,When a New York reporter plucks crocodile hunt...,16.072466,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""AU"", ""name"": ""Australia""}]",1986-09-26,328203506,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There's a little of him in all of us.,Crocodile Dundee,6.3,503
2452,16500000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,11093,"[{""id"": 582, ""name"": ""san francisco""}, {""id"": ...",en,House of Sand and Fog,"Behrani, an Iranian immigrant buys a Californi...",12.102725,"[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2003-12-19,16942795,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Some dreams can't be shared.,House of Sand and Fog,7.0,199

In [3]:
credit=pd.read_csv(r"C:\Date Science\Mechine Learning\movie_recommandation_dataset\tmdb_5000_credits.csv")
credit.sample(2)

,movie_id,title,cast,crew
47,54138,Star Trek Into Darkness,"[{""cast_id"": 2, ""character"": ""James T. Kirk"", ...","[{""credit_id"": ""52fe488dc3a36847f816d839"", ""de..."
651,196867,Annie,"[{""cast_id"": 6, ""character"": ""Annie Beckett"", ...","[{""credit_id"": ""52fe4d3c9251416c9110f435"", ""de..."

In [4]:
movies=movie.merge(credit,on='title')

In [5]:
movies.sample(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
3925,3000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 27, ""nam...",http://phantasm.com,15158,"[{""id"": 7939, ""name"": ""portal""}, {""id"": 12434,...",en,Phantasm II,"Mike, after his release from a psychiatric hos...",5.003615,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The ball is back!,Phantasm II,6.3,94,15158,"[{""cast_id"": 4, ""character"": ""Mike"", ""credit_i...","[{""credit_id"": ""535f7e3f0e0a264fde007a18"", ""de..."
4364,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,41469,"[{""id"": 10183, ""name"": ""independent film""}]",en,Next Stop Wonderland,A lighthearted story about a man and a woman w...,1.334481,[],...,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Romance Is Her Destination.,Next Stop Wonderland,6.0,20,41469,"[{""cast_id"": 3, ""character"": ""Erin Castleton"",...","[{""credit_id"": ""52fe45ccc3a36847f80daf45"", ""de..."
3880,2000000,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 18, ...",NaN,108346,"[{""id"": 14794, ""name"": ""lust""}, {""id"": 160780,...",en,Dreaming of Joseph Lees,Set in rural England in the 1950s Eva (Samanth...,0.116150,"[{""name"": ""Fox Entertainment Group"", ""id"": 857...",...,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Dreaming of Joseph Lees,8.0,1,108346,"[{""cast_id"": 5, ""character"": ""Joseph Lees"", ""c...","[{""credit_id"": ""52fe4a98c3a36847f81d7345"", ""de..."

columns that i need
1.budget
2.genres
3.id
4.cast
5.overview
6.crew
7.keywords

In [6]:
movies=movies[['id','title','overview','genres','keywords','cast','crew']]

In [7]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

0

Now we have to modify the columns and create a new column using existings
for thta first i have convert the datatype from string to list.

In [11]:
import ast

In [12]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [13]:
movies['genres']=movies['genres'].apply(convert)  #this will convert string to list

In [14]:
movies['keywords']=movies['keywords'].apply(convert)

In [15]:
#we will keep only top 3 actors from the cast column
def convert2(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
           l.append(i['name'])
           counter +=1
        else:
            break
    return l

In [16]:
movies['cast']=movies['cast'].apply(convert2)

In [17]:
movies.head(2)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

from crew we just need the director name

In [18]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [19]:
movies['crew']=movies['crew'].apply(fetch_director)

In [20]:
movies

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger]

for removing the space between names

In [21]:
def collapse(L):
    l1=[]
    for i in L:
        l1.append(i.replace(" ",""))
    return l1

In [22]:
movies['cast']=movies['cast'].apply(collapse)
movies['crew']=movies['crew'].apply(collapse)
movies['genres']=movies['genres'].apply(collapse)
movies['keywords']=movies['keywords'].apply(collapse)

In [23]:
movies

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

now convert the overview column into list

In [24]:
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [25]:
movies

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

In [26]:
movies['tag']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [27]:
new_df=movies[['id','title','tag']]

In [28]:
new_df.head()

,id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

here we will take similar words as same like love ,loving,loved etc using the following library.this it apply only on the string not in list

In [29]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [30]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y) # convert back to string

In [31]:
#join in space 
new_df['tag']=new_df['tag'].apply(lambda x : " ".join(x))

C:\Users\somna\AppData\Local\Temp\ipykernel_19372\3905464618.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x : " ".join(x))

In [32]:
new_df['tag'] = new_df['tag'].apply(stem)

C:\Users\somna\AppData\Local\Temp\ipykernel_19372\4074900442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(stem)

In [33]:
#make all words to lower case in tag
new_df['tag']=new_df['tag'].apply(lambda x: x.lower())

C:\Users\somna\AppData\Local\Temp\ipykernel_19372\3368323860.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x: x.lower())

Now we have to do text vectorization.
technique to convert text data to vector is "bags of words".

In [34]:
#to change word to vectors
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [35]:
vector=cv.fit_transform(new_df['tag']).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
vector.shape

(4806, 5000)

Now we will calculate the distance among the vectors.
we will cosine distance between vector i.e the angel between the vectors.
we use cosine distance because euclideian distance is not suitable for heigher dimensional space.

distance is inversely proposnal to similarity.

there is a function in sklearn for cosine distance calculation.

In [37]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)

In [38]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [43]:
new_df[new_df['title']=='Batman Begins'].index[0]

119

In [49]:
sorted(list(enumerate(similarity[new_df[new_df['title']=='Batman Begins'].index[0]])),reverse=True,key=lambda x :x[1])

[(119, 1.000000000000001),
 (65, 0.40218090755486674),
 (1361, 0.35434169344615046),
 (1360, 0.3340765523905305),
 (3, 0.3177444546511212),
 (3295, 0.3120099844792576),
 (4146, 0.3021836115095176),
 (9, 0.2988071523335985),
 (2248, 0.2895330120717931),
 (3823, 0.2886751345948129),
 (3730, 0.2770256256719071),
 (1248, 0.27533366183038216),
 (3259, 0.2750095491084634),
 (4103, 0.2693740118805895),
 (210, 0.26805548212375485),
 (1452, 0.2672612419124244),
 (4641, 0.2672612419124244),
 (2958, 0.26551033051027584),
 (1411, 0.2640084484055257),
 (428, 0.26058421928111053),
 (4139, 0.2598505751938437),
 (79, 0.25664471656093313),
 (3236, 0.25209208668275807),
 (813, 0.24817115320439403),
 (1254, 0.2451825928095098),
 (299, 0.24488368066812724),
 (697, 0.24365796154926905),
 (3308, 0.24325638628366392),
 (1883, 0.24307639633206166),
 (3645, 0.2417468892076141),
 (3339, 0.2409060279148579),
 (3334, 0.24053511772118197),
 (20, 0.2390457218668788),
 (2390, 0.23904572186687872),
 (711, 0.23845524161913303),
 (2257, 0.23622779563076704),
 (196, 0.23537827088100216),
 (4250, 0.23537827088100213),
 (1141, 0.23466983204052894),
 (3418, 0.23328473740792174),
 (1666, 0.23328473740792172),
 (4448, 0.23274807983626203),
 (3664, 0.23233508524700852),
 (2025, 0.23204774044612855),
 (1628, 0.23145502494313788),
 (1717, 0.23145502494313785),
 (1939, 0.23145502494313785),
 (3292, 0.2306582755049343),
 (1729, 0.2281052820616688),
 (4308, 0.22792115291927592),
 (1899, 0.2268161771816387),
 (2655, 0.22587697572631282),
 (3311, 0.22537446792760446),
 (4215, 0.22454435656953592),
 (3672, 0.2241632651332862),
 (970, 0.22333125014345934),
 (3980, 0.22291128503014115),
 (1200, 0.22242542101947538),
 (2030, 0.22237479499833038),
 (339, 0.22160131510697959),
 (1637, 0.2213555010378582),
 (2429, 0.22047927592204924),
 (1744, 0.22026692946430573),
 (1488, 0.21957751641342),
 (1444, 0.21957751641341997),
 (3813, 0.2193633988428327),
 (2595, 0.21912524504463884),
 (1794, 0.21886638465297897),
 (3380, 0.21870444131992664),
 (1396, 0.21821789023599245),
 (4529, 0.21715360605514816),
 (1988, 0.21709014165170287),
 (3484, 0.21709014165170287),
 (4383, 0.21614640663908807),
 (4781, 0.21600691233179373),
 (205, 0.21459876881973805),
 (808, 0.21459876881973805),
 (3075, 0.21459876881973802),
 (3874, 0.2142857142857143),
 (3091, 0.21428571428571427),
 (3456, 0.21428571428571427),
 (4020, 0.2138343008619249),
 (1009, 0.21239769762143665),
 (182, 0.21216710619787638),
 (409, 0.21216710619787638),
 (444, 0.21216710619787638),
 (2701, 0.21128856368212914),
 (4513, 0.21128856368212914),
 (4478, 0.21092395846882267),
 (3337, 0.21055872190307892),
 (450, 0.2105587219030789),
 (2487, 0.2105587219030789),
 (1042, 0.2096569673443837),
 (1249, 0.2096569673443837),
 (3769, 0.2091650066335189),
 (2510, 0.20869596778242056),
 (867, 0.20869596778242053),
 (193, 0.20766965266046605),
 (3945, 0.20659846763533435),
 (1537, 0.20659846763533432),
 (530, 0.2062571618313475),
 (4794, 0.20573779994945587),
 (939, 0.20535012709710013),
 (2961, 0.2053157732487465),
 (4783, 0.2041241452319315),
 (423, 0.2036532699906392),
 (313, 0.20328927815368153),
 (1136, 0.20328927815368153),
 (4665, 0.20328927815368153),
 (610, 0.20318886358684693),
 (3226, 0.2025671114728547),
 (2303, 0.2024809676835146),
 (2948, 0.20203050891044216),
 (2112, 0.20203050891044214),
 (4324, 0.20203050891044214),
 (4488, 0.2020305089104421),
 (3860, 0.20194517395039002),
 (2076, 0.20191135200894691),
 (3638, 0.20191135200894691),
 (2877, 0.2014557410063451),
 (2348, 0.20145574100634508),
 (3635, 0.20145574100634508),
 (1118, 0.20113458206170762),
 (4101, 0.20059435495071948),
 (2375, 0.20044593143431833),
 (1643, 0.2004459314343183),
 (3688, 0.2004459314343183),
 (3072, 0.2000330660496597),
 (4381, 0.2000330660496597),
 (1020, 0.20003306604965967),
 (3306, 0.1994310088043664),
 (4733, 0.1994310088043664),
 (1021, 0.199204768222399),
 (3636, 0.19920476822239896),
 (1815, 0.19906827984171396),
 (2748, 0.1988980632395388),
 (3676, 0.19889806323953876),
 (4408, 0.1985166667941861),
 (826, 0.19851666679418606),
 (482, 0.19820624179302296),
 (206, 0.1979720937587811),
 (2045, 0.19771864882368606),
 (2465, 0.19771864882368606),
 (2980, 0.19771864882368606),
 (60, 0.1966989481173608),
 (919, 0.19642857142857145),
 (3846, 0.19642857142857145),
 (1025, 0.19518001458970666),
 (4579, 0.19518001458970666),
 (4150, 0.19518001458970663),
 (1150, 0.1950473744013735),
 (3393, 0.1950473744013735),
 (3609, 0.19492029389636262),
 (4026, 0.1947984306184949),
 (4229, 0.19446111706564934),
 (1117, 0.19399589841579265),
 (1568, 0.19399589841579265),
 (4187, 0.19287918745261493),
 (3542, 0.1928791874526149),
 (4341, 0.19258222162991087),
 (3089, 0.19258222162991082),
 (2584, 0.19200614429492777),
 (2611, 0.19200614429492777),
 (1052, 0.19200614429492774),
 (3392, 0.19200614429492774),
 (4656, 0.19166296949998196),
 (1279, 0.1913694751757858),
 (1053, 0.19094065395649337),
 (782, 0.1909008870803031),
 (4780, 0.19068226087587872),
 (2508, 0.1906822608758787),
 (4801, 0.19030844390866536),
 (4067, 0.19015970731391624),
 (10, 0.1901597073139162),
 (3694, 0.18976802881914742),
 (1427, 0.18898223650461363),
 (2270, 0.18898223650461363),
 (3166, 0.18898223650461363),
 (3785, 0.18898223650461363),
 (4147, 0.18898223650461363),
 (3087, 0.1889822365046136),
 (868, 0.18820612547801763),
 (2209, 0.18820612547801763),
 (2863, 0.18820612547801763),
 (4453, 0.18820612547801763),
 (246, 0.18768337412695635),
 (3959, 0.18732688575387635),
 (758, 0.18712029714127995),
 (2088, 0.18712029714127995),
 (583, 0.18641092980036003),
 (1854, 0.18641092980036003),
 (3858, 0.1860968420796942),
 (2492, 0.18609684207969418),
 (3168, 0.18609684207969418),
 (3617, 0.18609684207969418),
 (1984, 0.18557687223952257),
 (2799, 0.18557687223952257),
 (2890, 0.18557687223952257),
 (3432, 0.18557687223952257),
 (4045, 0.18557687223952257),
 (1086, 0.18531232916527532),
 (1618, 0.18531232916527532),
 (2871, 0.18531232916527532),
 (4395, 0.18531232916527532),
 (3375, 0.1845254367394211),
 (3508, 0.18394180184548975),
 (2458, 0.18374210381479178),
 (2659, 0.18374210381479178),
 (252, 0.18374210381479175),
 (1260, 0.18344984642633574),
 (3766, 0.18344984642633574),
 (4226, 0.18344984642633572),
 (821, 0.1834498464263357),
 (3088, 0.18340630783632503),
 (232, 0.18333969940564224),
 (2769, 0.18333969940564224),
 (2919, 0.18333969940564224),
 (3800, 0.18333969940564224),
 (3801, 0.18333969940564224),
 (4630, 0.18311675519117862),
 (197, 0.18274347116195178),
 (238, 0.18274347116195178),
 (2771, 0.181848241863327),
 (1483, 0.18156825980064073),
 (4670, 0.18156825980064073),
 (3843, 0.18131016690571058),
 (264, 0.18093671611393647),
 (640, 0.18093671611393647),
 (512, 0.18070158058105026),
 (3299, 0.18070158058105024),
 (4667, 0.18070158058105024),
 (1870, 0.18018749253911182),
 (115, 0.1801874925391118),
 (1954, 0.1801874925391118),
 (1665, 0.1800205749557739),
 (3195, 0.1800205749557739),
 (3832, 0.1800205749557739),
 (4491, 0.1800205749557739),
 (4659, 0.1800205749557739),
 (1599, 0.1795813658232933),
 (4345, 0.1795813658232933),
 (2010, 0.17928429140015908),
 (3644, 0.17928429140015908),
 (3853, 0.17928429140015908),
 (3861, 0.17928429140015906),
 (3389, 0.17928429140015903),
 (4681, 0.17928429140015903),
 (893, 0.17917830008649063),
 (1255, 0.1785714285714286),
 (3947, 0.1785714285714286),
 (706, 0.17857142857142858),
 (1773, 0.1782560239768452),
 (2358, 0.1782560239768452),
 (2364, 0.17817416127494962),
 (716, 0.1781741612749496),
 (790, 0.1781741612749496),
 (3421, 0.17732484140379767),
 (4464, 0.17732484140379765),
 (1263, 0.17699808135119718),
 (4732, 0.17699808135119718),
 (921, 0.17695959932414138),
 (2678, 0.1767766952966369),
 (1742, 0.17574991006549875),
 (164, 0.17574991006549873),
 (3622, 0.17574991006549873),
 (3692, 0.17569105537498347),
 (3961, 0.17569105537498345),
 (448, 0.1754656015858991),
 (443, 0.17546560158589908),
 (471, 0.17546560158589908),
 (3729, 0.17546560158589908),
 (11, 0.17542826450672636),
 (1472, 0.1749635530559413),
 (2805, 0.1749635530559413),
 (3219, 0.1749635530559413),
 (4255, 0.1749635530559413),
 (3575, 0.17444940691627658),
 (1886, 0.17444940691627656),
 (4245, 0.17444940691627656),
 (1458, 0.1739722501598053),
 (592, 0.17397225015980528),
 (1091, 0.17397225015980528),
 (3738, 0.17397225015980528),
 (1776, 0.17393131069573453),
 (538, 0.1737020834449128),
 (664, 0.1737020834449128),
 (3555, 0.1737020834449128),
 (225, 0.17359126870735342),
 (997, 0.17359126870735342),
 (1466, 0.17359126870735342),
 (788, 0.1735912687073534),
 (714, 0.17342199390482402),
 (3532, 0.17342199390482402),
 (3653, 0.17342199390482402),
 (1809, 0.17323371679589583),
 (2501, 0.17291712531127046),
 (62, 0.17251638983558856),
 (591, 0.17251638983558856),
 (1875, 0.17251638983558856),
 (3827, 0.17251638983558856),
 (446, 0.1718107983722728),
 (1096, 0.1718107983722728),
 (2469, 0.1718107983722728),
 (3390, 0.1718107983722728),
 (4174, 0.1718107983722728),
 (576, 0.1711841970043652),
 (280, 0.17118419700436519),
 (844, 0.17118419700436519),
 (879, 0.17118419700436519),
 (3599, 0.17118419700436516),
 (963, 0.17109647770728875),
 (4275, 0.17109647770728875),
 (857, 0.17094086468945693),
 (1478, 0.17094086468945693),
 (2253, 0.17094086468945693),
 (2998, 0.17094086468945693),
 (4303, 0.17094086468945693),
 (4756, 0.17094086468945693),
 (1730, 0.1709408646894569),
 (3350, 0.1709408646894569),
 (4169, 0.1709408646894569),
 (1132, 0.17078251276599332),
 (1230, 0.17078251276599332),
 (3985, 0.17078251276599332),
 (4683, 0.17078251276599332),
 (3111, 0.17008401285415228),
 (1281, 0.1697336849583011),
 (2625, 0.16971105832553268),
 (599, 0.16940773179473462),
 (274, 0.16903085094570333),
 (2794, 0.16903085094570333),
 (4208, 0.16903085094570333),
 (1376, 0.1690308509457033),
 (1947, 0.1690308509457033),
 (4743, 0.16868694244915794),
 (4373, 0.1686133183583656),
 (1231, 0.16840826742715195),
 (2369, 0.16840826742715195),
 (4082, 0.16840826742715195),
 (2012, 0.16840826742715193),
 (1362, 0.16835875742536843),
 (2599, 0.16835875742536843),
 (2605, 0.16835875742536843),
 (954, 0.16800537625806178),
 (1722, 0.16800537625806178),
 (3022, 0.16800537625806178),
 (4452, 0.16800537625806178),
 (4578, 0.16800537625806178),
 (2297, 0.16794127653186058),
 (2221, 0.1675148485651225),
 (4639, 0.1675148485651225),
 (3300, 0.1673320053068151),
 (1668, 0.16718346377260587),
 (1039, 0.16703827619526523),
 (2346, 0.16703827619526523),
 (2357, 0.16703827619526523),
 (3731, 0.16703827619526523),
 (2062, 0.16695677422593644),
 (1044, 0.1669567742259364),
 (1178, 0.1669567742259364),
 (2242, 0.1667810962487478),
 (4674, 0.1667810962487478),
 (139, 0.16574838603294897),
 (1435, 0.16574838603294897),
 (282, 0.1652001970982293),
 (2940, 0.1652001970982293),
 (2156, 0.1649572197684645),
 (3900, 0.1649572197684645),
 (727, 0.16488754406534833),
 (3104, 0.1647172818672541),
 (673, 0.16448792373994223),
 (1415, 0.16448792373994223),
 (2191, 0.16434393378347914),
 (493, 0.16414978848973424),
 (1847, 0.16366341767699433),
 (3209, 0.16366341767699433),
 (69, 0.1636634176769943),
 (2119, 0.1636634176769943),
 (2246, 0.1636634176769943),
 (2336, 0.1636634176769943),
 (2653, 0.1636634176769943),
 (2803, 0.1636634176769943),
 (3378, 0.1636634176769943),
 (3902, 0.1636634176769943),
 (4465, 0.1636634176769943),
 (1085, 0.16366341767699427),
 (2416, 0.16366341767699427),
 (4142, 0.16366341767699427),
 (1955, 0.1633263145020371),
 (316, 0.16325578711208483),
 (1499, 0.16325578711208483),
 (1910, 0.1632557871120848),
 (672, 0.16283473681973243),
 (1418, 0.16283473681973243),
 (1855, 0.16283473681973243),
 (2053, 0.16283473681973243),
 (2935, 0.16283473681973243),
 (2567, 0.1628347368197324),
 (1026, 0.16205093088804112),
 (747, 0.1620509308880411),
 (4785, 0.1620509308880411),
 (4233, 0.16116459280507608),
 (557, 0.16116459280507606),
 (1297, 0.16116459280507606),
 (1948, 0.16116459280507606),
 (2179, 0.16116459280507606),
 (3010, 0.16116459280507606),
 (3593, 0.16116459280507606),
 (286, 0.1608723630219467),
 (2150, 0.16071428571428573),
 (2921, 0.16071428571428573),
 (152, 0.16042223697993696),
 (405, 0.16042223697993696),
 (1399, 0.16035674514745465),
 (4403, 0.16035674514745465),
 (1783, 0.16035674514745463),
 (1707, 0.15943703480442334),
 (962, 0.15936381457791918),
 (1559, 0.15936381457791918),
 (1966, 0.15936381457791918),
 (2211, 0.15936381457791918),
 (2362, 0.15936381457791918),
 (3030, 0.15936381457791918),
 (4435, 0.15936381457791918),
 (652, 0.15929827321607748),
 (2107, 0.15929827321607748),
 (1184, 0.15929827321607745),
 (1329, 0.15929827321607745),
 (710, 0.15859036992388778),
 (1320, 0.15859036992388778),
 (4592, 0.15859036992388778),
 (283, 0.15811388300841897),
 (1194, 0.15811388300841897),
 (1945, 0.15811388300841897),
 (2440, 0.15811388300841897),
 (2657, 0.15811388300841897),
 (217, 0.15791904142730917),
 (1018, 0.15791904142730917),
 (1813, 0.15791904142730917),
 (3106, 0.15791904142730917),
 (823, 0.15762208124782015),
 (1784, 0.15762208124782015),
 (2541, 0.15759377014184453),
 (1204, 0.15748519708717804),
 (2224, 0.15724272550828777),
 (2591, 0.15724272550828777),
 (3552, 0.15724272550828777),
 (3684, 0.15724272550828777),
 (3818, 0.15724272550828777),
 (3977, 0.15724272550828777),
 (4004, 0.15724272550828777),
 (3585, 0.15669579263200217),
 (4518, 0.15663787513136096),
 (1242, 0.15657502514382474),
 (607, 0.15640281177246362),
 (1171, 0.15640281177246362),
 (3946, 0.15640281177246362),
 (387, 0.1559362351170901),
 (1221, 0.1559362351170901),
 (2723, 0.1559362351170901),
 (3346, 0.1559362351170901),
 (3702, 0.1559362351170901),
 (2979, 0.1559023911155809),
 (3515, 0.1559023911155809),
 (3571, 0.1559023911155809),
 (1197, 0.15590239111558088),
 (1805, 0.15590239111558088),
 (3433, 0.15590239111558088),
 (551, 0.15534244150030002),
 (824, 0.15534244150030002),
 (1367, 0.15534244150030002),
 (2077, 0.15534244150030002),
 (3605, 0.1552647508520297),
 (2003, 0.15430334996209194),
 (4567, 0.15430334996209194),
 (4697, 0.15430334996209194),
 (877, 0.1543033499620919),
 (2033, 0.1543033499620919),
 (1852, 0.1540912490371446),
 (2066, 0.1540912490371446),
 (1189, 0.15398682993655988),
 (1743, 0.1537811713073114),
 (1957, 0.1537811713073114),
 (2548, 0.1537811713073114),
 (3814, 0.1537811713073114),
 (4311, 0.1537811713073114),
 (4727, 0.1537811713073114),
 (1038, 0.15328483487124145),
 (1413, 0.15328483487124145),
 (3301, 0.15328483487124145),
 (4412, 0.15328483487124145),
 (1343, 0.15325150845822202),
 (3159, 0.1527399524929794),
 (129, 0.1527207096642425),
 (335, 0.1527207096642425),
 (3934, 0.1527207096642425),
 (4238, 0.1527207096642425),
 (4413, 0.1527207096642425),
 (3825, 0.15242534875526564),
 (1525, 0.15228622596829317),
 (1384, 0.151744244666721),
 (1616, 0.151744244666721),
 (2220, 0.151744244666721),
 (2790, 0.151744244666721),
 (2854, 0.151744244666721),
 (4132, 0.151744244666721),
 (4140, 0.151744244666721),
 (4154, 0.151744244666721),
 (4162, 0.151744244666721),
 (3121, 0.15152288168283162),
 (562, 0.1515228816828316),
 (615, 0.1515228816828316),
 (1050, 0.1515228816828316),
 (1421, 0.1515228816828316),
 (2344, 0.1515228816828316),
 (4559, 0.15130688316720062),
 (3095, 0.15120368418975152),
 (2906, 0.1511857892036909),
 (3105, 0.1511857892036909),
 (388, 0.15118578920369088),
 (3369, 0.15118578920369088),
 (2382, 0.1508123367044475),
 (38, 0.15033444857573872),
 (174, 0.14978617237881955),
 (500, 0.14978617237881955),
 (2207, 0.14978617237881955),
 (4374, 0.14978617237881955),
 (1193, 0.14978617237881953),
 (1456, 0.14978617237881953),
 (2325, 0.14978617237881953),
 (4459, 0.14978617237881953),
 (171, 0.14969623771302396),
 (575, 0.14969623771302396),
 (1079, 0.14969623771302396),
 (1538, 0.14969623771302396),
 (1195, 0.14940357616679922),
 (2293, 0.14940357616679922),
 (1308, 0.1494035761667992),
 (2768, 0.1494035761667992),
 (2923, 0.1494035761667992),
 (3807, 0.1494035761667992),
 (3994, 0.1494035761667992),
 (4454, 0.1494035761667992),
 (4562, 0.1494035761667992),
 (4627, 0.14917354742965408),
 (4706, 0.14896778454477172),
 (137, 0.14888750009563956),
 (247, 0.14888750009563956),
 (1002, 0.14888750009563956),
 (3354, 0.14888750009563956),
 (3596, 0.14888750009563956),
 (3798, 0.14848604296791068),
 (560, 0.14847846772912465),
 (1104, 0.14847846772912465),
 (132, 0.14824986333222026),
 (140, 0.14824986333222026),
 (2235, 0.14824986333222026),
 (2359, 0.14824986333222026),
 (2571, 0.14824986333222026),
 (3361, 0.14824986333222026),
 (4186, 0.14824986333222026),
 (4451, 0.14824986333222026),
 (103, 0.148039131365948),
 (1689, 0.148039131365948),
 (2915, 0.148039131365948),
 (4382, 0.148039131365948),
 (1649, 0.14790199457749043),
 (14, 0.1479019945774904),
 (96, 0.1479019945774904),
 (112, 0.1479019945774904),
 (2154, 0.1479019945774904),
 (3057, 0.1479019945774904),
 (3443, 0.1479019945774904),
 (4522, 0.14788012043781928),
 (4223, 0.14734721736971537),
 (491, 0.14693020840087634),
 (3379, 0.14693020840087634),
 (2545, 0.1469302084008763),
 (2347, 0.1468446196428705),
 (3102, 0.1468446196428705),
 (3877, 0.1468446196428705),
 (292, 0.14638501094227999),
 (1582, 0.14638501094227999),
 (1829, 0.14638501094227999),
 (2236, 0.14638501094227999),
 (2244, 0.14638501094227999),
 (4328, 0.14638501094227999),
 (983, 0.14626418136251404),
 (851, 0.1460871774476944),
 (883, 0.1460871774476944),
 (1507, 0.1460871774476944),
 (163, 0.14608717744769437),
 (2373, 0.14608717744769437),
 (2819, 0.14608717744769437),
 (3181, 0.14608717744769437),
 (613, 0.1458029608799511),
 (1406, 0.1458029608799511),
 (2309, 0.1458029608799511),
 (2759, 0.1458029608799511),
 (2978, 0.1458029608799511),
 (4133, 0.1458029608799511),
 (1115, 0.14547859349066158),
 (2023, 0.14547859349066158),
 (2298, 0.14547859349066158),
 (1487, 0.14503758572005868),
 (3650, 0.1449427589131121),
 (285, 0.14478512671975205),
 (2726, 0.14433756729740646),
 (1092, 0.14433756729740643),
 (1884, 0.14433756729740643),
 (1909, 0.14433756729740643),
 (2383, 0.14433756729740643),
 (2684, 0.14426644752600448),
 (386, 0.14414999403128945),
 (2400, 0.14414999403128945),
 (518, 0.14414999403128942),
 (1857, 0.14409760442605873),
 (122, 0.14400460822119582),
 (1124, 0.14400460822119582),
 (1423, 0.14400460822119582),
 (1436, 0.14400460822119582),
 (2312, 0.14400460822119582),
 (3261, 0.14400460822119582),
 (3513, 0.14400460822119582),
 (3763, 0.14400460822119582),
 (4119, 0.14400460822119582),
 (4585, 0.14400460822119582),
 (1532, 0.14374722712498647),
 (1920, 0.14374722712498647),
 (2287, 0.14374722712498647),
 (4319, 0.1434511460132578),
 (281, 0.14285714285714288),
 (1555, 0.14285714285714288),
 (3273, 0.14285714285714288),
 (1529, 0.14285714285714285),
 (2048, 0.14285714285714285),
 (3246, 0.14285714285714285),
 (3760, 0.14285714285714285),
 (969, 0.142731332931499),
 (2513, 0.142731332931499),
 (3677, 0.142731332931499),
 (545, 0.14264935053936392),
 (1068, 0.14264935053936392),
 (1457, 0.14264935053936392),
 (2009, 0.14264935053936392),
 (3876, 0.14264935053936392),
 (4166, 0.14264935053936392),
 (4644, 0.14264935053936392),
 (3649, 0.14245072057454744),
 (1234, 0.1424507205745474),
 (2478, 0.1424507205745474),
 (4195, 0.1424507205745474),
 (3808, 0.14229360163537472),
 (676, 0.1417366773784602),
 (700, 0.1417366773784602),
 (761, 0.1417366773784602),
 (974, 0.1417366773784602),
 (1925, 0.1417366773784602),
 (4037, 0.1417366773784602),
 (4591, 0.1417366773784602),
 (1113, 0.14159846508095775),
 (1305, 0.14159846508095775),
 (1816, 0.14159846508095775),
 (1949, 0.1411862416005035),
 (7, 0.14101901870444156),
 (535, 0.14101901870444156),
 (729, 0.14101901870444156),
 (1659, 0.14101901870444156),
 (1782, 0.14101901870444156),
 (2052, 0.14101901870444156),
 (3063, 0.14101901870444156),
 (3182, 0.14101901870444156),
 (3470, 0.14101901870444156),
 (2082, 0.14076253059521726),
 (750, 0.14037248126871926),
 (3190, 0.14037248126871926),
 (496, 0.14008295367013146),
 (2001, 0.13980819735027003),
 (2363, 0.13980819735027003),
 (1663, 0.13957263155977065),

In [50]:
def recommend(movie):
       index=new_df[new_df['title']==movie].index[0]
       distances=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x :x[1])
       for i  in distances[1:6]:
              print(new_df.iloc[i[0]].title)

In [51]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

Now to bulid a website for this we use pickle